[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "nasimemu-enhanced"
dynamic = ["version"]
authors = [
    {name="Jaromir Janisch", email="author@jaromiru.com"}
]
maintainers = [
    {name="dreamfarer"}
]
description = "Gymnasium based environment for training offensive RL agents in simulated and emulated computer networks."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "gymnasium==1.3",
    "networkx", # For nasim render
    "prettytable", # For nasim render
    "matplotlib", # For nasim render (suppress warning)
    "pyyaml", # For nasim
    "pymetasploit3 == 1.0.6", # Metasploit RPC client for emulation
    "requests", # For msf_interface shared session
    "retry", # For msf_interface shared session
    "plotly", # For nasim_problem debug
    "scipy", # For networkx
    "numpy==2.2.6",
]

[project.urls]
Homepage = "https://github.com/dreamfarer/NASimEmu-Enhanced"
Repository = "https://github.com/dreamfarer/NASimEmu-Enhanced"
Upstream = "https://github.com/jaromiru/NASimEmu"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.sdist]
only-include = ["src", "README.md", "LICENSE", "pyproject.toml"]

[tool.hatch.build.targets.wheel]
packages = ["src/nasimemu"]

[tool.mypy]
python_version = "3.10"
strict = true
files = ["src/nasimemu"]

[[tool.mypy.overrides]]
module = ["matplotlib.*", "plotly.*", "prettytable.*", "pymetasploit3.*"]
ignore_missing_imports = true
