""" The main Environment class for NASim: NASimEnv.

The NASimEnv class is the main interface for agents interacting with NASim.
"""
from typing import TYPE_CHECKING, Any

import gymnasium as gym
from numpy.typing import NDArray
from gymnasium import spaces

from .state import State
from .render import Viewer
from .network import Network
from .observation import Observation
from .action import Action, ParameterisedActionSpace

if TYPE_CHECKING:
    from nasimemu.nasim.scenarios.scenario import Scenario


class NASimEnv(gym.Env[Any, Any]):
    """ A simulated computer network environment for pen-testing.

    Implements the Gymnasium interface.

    ...

    Attributes
    ----------
    name : str
        the environment scenario name
    scenario : Scenario
        Scenario object, defining the properties of the environment
    action_space : ParameterisedActionSpace
        Action space for environment. This is a parameterised action space
        (which subclasses gym.spaces.MultiDiscrete), so each action is
        represented using a list of parameters.
    observation_space : gym.spaces.Box
        observation space for environment. Observations are represented as
        a 2D matrix.
    current_state : State
        the current state of the environment
    last_obs : Observation
        the last observation that was generated by environment
    steps : int
        the number of steps performed since last reset (this does not include
        generative steps)
    """
    metadata = {'rendering.modes': ["readable"]}
    reward_range = (-float('inf'), float('inf'))

    action_space: ParameterisedActionSpace
    observation_space: spaces.Box | None = None  # type: ignore[assignment]  # no observation space is defined yet
    current_state: State
    last_obs: Observation | None = None

    def __init__(self,
                 scenario: "Scenario",
                 fully_obs: bool = False) -> None:
        """
        Parameters
        ----------
        scenario : Scenario
            Scenario object, defining the properties of the environment
        fully_obs : bool, optional
            The observability mode of environment, if True then uses fully
            observable mode, otherwise is partially observable (default=False)
        """
        self.name = scenario.name
        self.scenario = scenario
        self.fully_obs = fully_obs

        self.network = Network(scenario)
        self.current_state = State.generate_initial_state(self.network)
        self._renderer: Viewer | None = None
        # self.reset()

        self.action_space = ParameterisedActionSpace(self.scenario)

        self.steps = 0

    def reset(
        self, *, seed: int | None = None, options: dict[str, Any] | None = None
    ) -> tuple[NDArray[Any], dict[str, Any]]:
        """Reset the state of the environment and returns the initial state.

        Implements gymnasium.Env.reset().

        Returns
        -------
        numpy.Array
            the initial observation of the environment
        dict
            auxiliary information (empty)
        """
        super().reset(seed=seed)
        self.steps = 0
        self.current_state = self.network.reset(self.current_state)
        self.last_obs = self.current_state.get_initial_observation(
            self.fully_obs
        )

        return self.last_obs.numpy(), {}

    def step(
        self, action: Any
    ) -> tuple[NDArray[Any], float, bool, bool, dict[str, Any]]:
        """Run one step of the environment using action.

        Implements gymnasium.Env.step().

        Parameters
        ----------
        action : Action or int or list or NumpyArray
            Action to perform. If not Action object, then this should be
            an indexable array.

        Returns
        -------
        numpy.Array
            observation from performing action
        float
            reward from performing action
        bool
            whether the goal has been reached
        bool
            whether the step limit of the scenario has been reached
        dict
            auxiliary information regarding step
            (see :func:`nasim.env.action.ActionResult.info`)
        """
        next_state, obs, reward, terminated, info = self.generative_step(
            self.current_state,
            action
        )
        self.current_state = next_state
        self.last_obs = obs

        obs_array = obs.numpy()

        self.steps += 1

        truncated = (
            not terminated
            and self.scenario.step_limit is not None
            and self.steps >= self.scenario.step_limit
        )

        return obs_array, reward, terminated, truncated, info

    def generative_step(
        self, state: State, action: Any
    ) -> tuple[State, Observation, float, bool, dict[str, Any]]:
        """Run one step of the environment using action in given state.

        Parameters
        ----------
        state : State
            The state to perform the action in
        action : Action, int, list, NumpyArray
            Action to perform. If not Action object, then this should be
            an indexable array.

        Returns
        -------
        State
            the next state after action was performed
        Observation
            observation from performing action
        float
            reward from performing action
        bool
            whether the episode has ended or not
        dict
            auxiliary information regarding step
            (see :func:`nasim.env.action.ActionResult.info`)
        """
        if not isinstance(action, Action):
            action = self.action_space.get_action(action)

        next_state, action_obs = self.network.perform_action(
            state, action
        )
        obs = next_state.get_observation(
            action, action_obs, self.fully_obs
        )
        done = self.goal_reached(next_state)
        reward = action_obs.value - action.cost
        return next_state, obs, reward, done, action_obs.info()

    def generate_initial_state(self) -> State:
        """Generate the initial state for the environment.

        Returns
        -------
        State
            The initial state

        Notes
        -----
        This does not reset the current state of the environment (use
        :func:`reset` for that).
        """
        return State.generate_initial_state(self.network)

    def render(
        self,
        mode: str = "readable",
        obs: Observation | NDArray[Any] | None = None
    ) -> None:
        """Render observation.

        See render module for more details on modes and symbols.

        Parameters
        ----------
        mode : str
            rendering mode
        obs : Observation or numpy.ndarray, optional
            the observation to render, if None will render last observation.
            If numpy.ndarray it must be in format that matches Observation
            (i.e. ndarray returned by step method) (default=None)
        """
        if obs is None:
            obs = self.last_obs

        assert obs is not None
        if not isinstance(obs, Observation):
            obs = Observation.from_numpy(obs, self.current_state.shape())

        if self._renderer is None:
            self._renderer = Viewer(self.network)

        if mode == "readable":
            self._renderer.render_readable(obs)
        else:
            print(
                "Please choose correct render mode from :"
                f"{self.metadata['rendering.modes']}"
            )

    def render_state(
        self,
        mode: str = "readable",
        state: State | NDArray[Any] | None = None
    ) -> None:
        """Render state.

        See render module for more details on modes and symbols.

        If mode = ASCI:
            Machines displayed in rows, with one row for each subnet and
            hosts displayed in order of id within subnet

        Parameters
        ----------
        mode : str
            rendering mode
        state : State or numpy.ndarray, optional
            the State to render, if None will render current state
            If numpy.ndarray it must be in format that matches State
            (i.e. ndarray returned by generative_step method) (default=None)
        """
        if state is None:
            state = self.current_state

        if not isinstance(state, State):
            state = State.from_numpy(state,
                                     self.current_state.shape(),
                                     self.current_state.host_num_map)

        if self._renderer is None:
            self._renderer = Viewer(self.network)

        if mode == "readable":
            self._renderer.render_readable_state(state)
        else:
            print("Please choose correct render mode from :"
                  f"{self.metadata['rendering.modes']}")

    def goal_reached(self, state: State | None = None) -> bool:
        """Check if the state is the goal state.

        The goal state is when all sensitive hosts have been compromised.

        Parameters
        ----------
        state : State, optional
            a state, if None will use current_state of environment
            (default=None)

        Returns
        -------
        bool
            True if state is goal state, otherwise False.
        """
        if state is None:
            state = self.current_state
        return self.network.all_sensitive_hosts_compromised(state)

    def __str__(self) -> str:
        output = [
            "NASimEnv:",
            f"name={self.name}",
            f"fully_obs={self.fully_obs}"
        ]
        return "\n  ".join(output)
